### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'query')

### ISSUE THREAD

**Issue by import-brain** [avitorio/outstatic#1]
Hi, I've been trying to replace my current CMS on my website with Outstatic. I followed the documentation and was able to get to where I got the "sign in with GitHub" screen, but after I authorized the OAuth app, it redirected back to localhost and errored out with "TypeError: Cannot read properties of null (reading 'query')". Could you please help me on this? Thank you so much!

<img width="1054" alt="Screenshot 2022-10-21 at 11 30 23 PM" src="https://user-images.githubusercontent.com/68196762/197317233-53b30132-e0df-4dc7-a0d7-18e8ced0586d.png">

**Comment by avitorio** [comment]
Hey @import-brain 
Thanks for flagging this. I'll take a look at it over the weekend.

**Comment by import-brain** [comment]
> Hey @import-brain Thanks for flagging this. I'll take a look at it over the weekend.

Thank you!

**Comment by avitorio** [comment]
@import-brain Would you be able to create a repo were I could try to reproduce the error?

**Comment by import-brain** [comment]
> @import-brain Would you be able to create a repo were I could try to reproduce the error?

Could you please clarify what you mean? Do you want a repo with Next and Outstatic set up?

**Comment by avitorio** [comment]
@import-brain Sorry, for not clarifying. If you could create a minimal clone of your current repository and make it public so I can check it out, that'd be great. 

I have created a Discord server for the project, so if you want to reach out to me over there perhaps we could solve this quickly together: https://discord.gg/kBz3u7cA

Cheers!

**Comment by import-brain** [comment]
> @import-brain Sorry, for not clarifying. If you could create a minimal clone of your current repository and make it public so I can check it out, that'd be great.
> 
> I have created a Discord server for the project, so if you want to reach out to me over there perhaps we could solve this quickly together: [discord.gg/kBz3u7cA](https://discord.gg/kBz3u7cA)
> 
> Cheers!

I used `create-next-app` to try to reproduce the error, but it worked perfectly first try. How odd... it has to do with how the real site is configured. I'll join the Discord.

**Comment by avitorio** [comment]
Ok, closing this. :)

**Comment by tinspham209** [comment]
Same error with my current website, but when I update `next` version, from `12.2.3` to `12.3.1`, this error is fixed!

**Comment by import-brain** [comment]
> Same error with my current website, but when I update `next` version, from `12.2.3` to `12.3.1`, this error is fixed!

@tinspham209 Just tried this, and it worked! Thank you so much!

**Comment by import-brain** [comment]
Should we add something to the documentation like "requires next version 12.3.1"?

**Comment by avitorio** [comment]
Hey @import-brain and @tinspham209 - I've just updated outstatic to `0.0.32-rc`.
This new version should work on Next.js `^13.0.0` as well as `^12.0.0`!

Let me know if works for you!

**Comment by import-brain** [comment]
> Hey @import-brain and @tinspham209 - I've just updated outstatic to `0.0.32-rc`. This new version should work on Next.js `^13.0.0` as well as `^12.0.0`!
> 
> Let me know if works for you!

Works fine for me! Thank you!
