### ISSUE TITLE
Could not resolve to a Repository with the name ...

### ISSUE THREAD

**Issue by qlereboursBS** [avitorio/outstatic#10]
Hi,
First, thanks for the tool which really hypes me and my team!
I don't know if I did something wrong or not but I got the following error:

`Could not resolve to a Repository with the name 'qlereboursBS/traveledmap/traveledmap-outstatic-blog'`
When my GitHub account is qlereboursBS, but the repository is under an organization I own called traveledmap.

My .env contains `OST_REPO_SLUG=traveledmap/traveledmap-outstatic-blog`.

I also transfered both the gh app and repository from qlereboursBS to traveledmap after I started to install outstatic (I revoked all tokens, deleted the `ost_token` in localstorage and cleared the `next` folder).

It's very likely that you use the GitHub acocunt name as a prefix for the repository, but what if the repository is under an organization?

Thanks

**Comment by avitorio** [comment]
Hi @qlereboursBS,

There's actually an environment variable called `OST_REPO_OWNER` which should help you fix this.

A full description of the available [environment variables](https://outstatic.com/docs/environment-variables) is available in the docs.

I thought I had added that page to the menu, but it was lacking. So your issue served as a reminder.
Let me know if updating the `OST_REPO_OWNER` variable solves your problem so we can close this issue! Cheers!

**Comment by qlereboursBS** [comment]
Awesome, thank you.
I tried and I don't have the error anymore
(I have another error related to `[this issue](https://github.com/avitorio/outstatic/issues/1)` but I need to retry configuring it. If I still have an problem, I'll create another issue.

I think I can close this one since the environment variable page is in the doc now :)
