### ISSUE TITLE
No such file or directory — `.gitkeep.md`

### ISSUE THREAD

**Issue by mamunonweb** [avitorio/outstatic#11]
Currently, the existence of files other than `mdx?` (ex: `.gitkeep`) within a collection folder results in an error:

`Error: ENOENT: no such file or directory, open "blog/outstatic/content/posts/.gitkeep.md"`

**Comment by mamunonweb** [comment]
@avitorio @clemmurphy 

I think as slugs we should only consider `mdx?` files name (without extension).

```ts
// now
getDocumentSlugs('posts') // ['post-1.md', 'post-2.mdx', 'images', '.gitkeep']

// then
getDocumentSlugs('posts') // ['post-1', 'post-2']
```

**Comment by avitorio** [comment]
Hey @mamunonweb,
I wasn't aware this was happening. 
I'll take a look at it and try to create a fix sometime this week. Feel free to try to fix it yourself and create a PR if possible. 
Cheers!
