### ISSUE TITLE
Incorrect Page Title Display on Detail Page

### ISSUE THREAD

**Issue by xinzhi** [avitorio/outstatic#112]
### Provide environment information

Page: https://outstatic-dev-blog-8qilismfg-andrevitorio.vercel.app/posts/nothing-wrong

### What browser are you using? (if relevant)

Chrome/114.0.0.0

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Actual Title: Outstatic

### Expected Behavior

Expected Title: Nothing is wrong. Everything is perfect | Outstatic

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/avitorio/outstatic/tree/canary/examples/blog

### To Reproduce

I have identified an issue while comparing the following two pages:

Link 1: https://outstatic-dev-blog-8qilismfg-andrevitorio.vercel.app/posts/nothing-wrong
Link 2: https://outstatic-example-blog.vercel.app/posts/nothing-wrong

To Reproduce:
To reproduce the issue, please follow the steps below:

- Open both links provided above in separate browser tabs.
- Carefully compare the content and layout of the pages.
- Observe the differences between the two pages.

**Comment by avitorio** [comment]
Hey @xinzhi Thanks for bringing this up to our attention. 

I might have removed the title and other metadata part of the deploy with vercel blog when updating it to use the `/app` directory.

Let me know if you'd like to try adding the [metadata API ](https://nextjs.org/docs/app/building-your-application/optimizing/metadata)to the example blog.
You'd need to add it to `/apps/dev` and `/examples/blog` in our repository.

**Comment by avitorio** [comment]
Hey @xinzhi, 
Just wanted to let you know I've fixed this. Thanks for flagging this! :)
