### ISSUE TITLE
Creating a new collection doesn't creates something on the website

### ISSUE THREAD

**Issue by Prottoy2938** [avitorio/outstatic#128]
### Provide environment information

Nextjs latest, Outstatic latest

### Describe the Bug

I'm following the default get started guide on the documentation. Whenever I'm creating a new collection & adding blogs on that collection, nothing gets added to the site. The new collection & its content doesn't shows up. The website only shows `Posts` & `Projects` collecton & nothing else

### Expected Behavior

Should show the collection

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://outstatic.com/docs/getting-started

### To Reproduce

Follow the default getting started process as described in the documentation file

**Comment by Prottoy2938** [comment]
Is it possible to do the whole process automatically?

**Comment by avitorio** [comment]
It is possible but requires some setup. You can make it so that new collections create new pages on the site, that would require you to use a dynamic route and fetch each collection so the front end knows what to display...
