### ISSUE TITLE
Code highlight doesn't works on the deployed blogs

### ISSUE THREAD

**Issue by Prottoy2938** [avitorio/outstatic#129]
### Provide environment information

Latest nextjs & outstatic

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Code highlight on the outstatic dashboard, but not on the deployed blog

### Expected Behavior

Should highlight the code on the deployed blog

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

No link

### To Reproduce

Just try creating a codesnippet & check the blog.

**Comment by avitorio** [comment]
The blog is barebones, it is supposed to only have basic features. You can check the code under `/apps/web` to see an example of code that uses code highlight.
