### ISSUE TITLE
Cover Image upload does not work when using Safari as the browser.

### ISSUE THREAD

**Issue by ZiyadBoshima** [avitorio/outstatic#135]
### Provide environment information

Next: 13.4.19

React: 18.2.0

Outstatic: Version 0.0.39

Safari: Version 15.3 (17612.4.9.1.8)

### What browser are you using? (if relevant)

Safari 15.3 (17612.4.9.1.8)

### How are you deploying your application? (if relevant)

With Vercel

### Describe the Bug

 Uploading an image using a link works fine. Uploading a file directly will trigger an error on the webpage for a split second: "The image failed to load, try submitting again."

### Expected Behavior

I expect the image to be loaded for preview, and uploaded upon clicking on "Save".

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/ZiyadBoshima/minimal-blog-template

### To Reproduce

Steps to reproduce the problem:

1. Pull the linked repo
2. Run `npm i`
3. Follow the Outstatic documentations to setup the environmental variables as well as GitHub authentication
4. Run `npm run dev`
5. On **Safari** go to http://localhost:3000/outstatic and sign in.
6. Go to the posts collection and create a new post
7. Click on Cover Image, and then add an image from a file.

When you do step 7, you should see an image preview, then a red text for a split second, and then the image and red text disappear.

**Comment by avitorio** [comment]
Thank you for creating this issue!

**Comment by avitorio** [comment]
Fixed by #146
