### ISSUE TITLE
Can't create any blogs if the title is in another language

### ISSUE THREAD

**Issue by Prottoy2938** [avitorio/outstatic#138]
### Provide environment information

nextjs 13, latest outstatic

### Describe the Bug

I can't create any blogs if the title is in another language. For example, if I create a blog with this title: ( তৃণভোজী এই ডাইনোসর কত বড় ছিল? ) then the blog breaks..

The dashboard UI doesn't lets me edit it or it doesn't publish.

I think the issue might be related with the url slug & the language the title is in.

Whats the fix?

### Expected Behavior

Should be able to create a blog if the title is in a different language

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

No link atm

### To Reproduce

Just create a blog with this title: তৃণভোজী এই ডাইনোসর কত বড় ছিল?

**Comment by avitorio** [comment]
Hey @Prottoy2938,
Sorry you experienced this. What would be the expected slug for a title like that?

**Comment by Prottoy2938** [comment]
Just the same title, where the *spaces* are replaced with a *dash* `-`. 

E.g: তৃণভোজী এই ডাইনোসর কত বড় ছিল?**=>** তৃণভোজী-এই-ডাইনোসর-কত-বড়-ছিল

Or maybe just a randomly generated string if that's easier: `wew112218218`


Currently if you write the title in a different language then no slug is added.

**Comment by avitorio** [comment]
Does github accept filenames with these characters? Would you be able to fork outstatic and try to fix this?

**Comment by avitorio** [comment]
@Prottoy2938 this has been fixes. It will be available in our next version.

**Comment by avitorio** [comment]
You can use this installing version `1.0.0-canary.4`
