### ISSUE TITLE
Feature Request: Image Compression

### ISSUE THREAD

**Issue by paulnorthup** [avitorio/outstatic#14]
First off - I love what you've built, and I love the simplicity of it.

Some quick profiling on the front-end looks like images uploaded are not optimized, so I end up serving 2MB images. They're fast for me, but they're not fast in general.

I haven't gotten into your source to see what can be done, but I'm curious if you'd consider adding compressorjs for image compression before saving the file in the content editor. So far that's the only thing I would love to see!

I really appreciate how quick this is to set up, and how simple and content-focused the act of managing content becomes. Seriously - nice work!!

**Comment by avitorio** [comment]
Hi @paulnorthup,

Thanks for the suggestion and kind words. I'm glad you like the project!

We definitely want to improve how images are processed but the project is in its early days and we are prioritizing making the library stable by fixing bugs and other more critical issues.

For now we'll  keep images exactly as they are uploaded. You can always optimize them on your computer before uploading. 

In the future you can use the [Ideas](https://github.com/avitorio/outstatic/discussions/categories/ideas) discussion tab for these suggestions. All the best!
