### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by guiibraun** [avitorio/outstatic#15]
I have an error when building the project on Vercel

![image](https://user-images.githubusercontent.com/65604906/197874856-7fd1ff24-9986-4500-879b-7be22740cfdc.png)

**Comment by avitorio** [comment]
Thanks @guiibraun. We are aware of this error and are working on it now.
Apparently the recent release of next 13 removed the `layout` prop from `next/image`

**Comment by avitorio** [comment]
Hey @guiibraun, although this is closed I wanted to say the update is now live and you can deploy Outstatic with Vercel again! Cheers!

**Comment by guiibraun** [comment]
> Hey @guiibraun, although this is closed I wanted to say the update is now live and you can deploy Outstatic with Vercel again! Cheers!
> 

Thank you so much 😅
