### ISSUE TITLE
Custom fields as columns in collection table

### ISSUE THREAD

**Issue by avitorio** [avitorio/outstatic#153]
I would like it if custom fields showed up in a collection's table.

Something like when creating a custom field, adding a boolean for "display in table"

If that boolean is checked, then when looking at a collection table, that field becomes a column.

I am happy to take a stab at this and create a PR if there is interest in this.

_Originally posted by @city41 in https://github.com/avitorio/outstatic/discussions/152_

**Comment by ZiyadBoshima** [comment]
Hey Andre! This is a good feature to have, especially in making Outstatic a little more customizable. I personally can make use of this feature (for seeing a post's tags for example). I would like to give this a try.

**Comment by avitorio** [comment]
Hey @ZiyadBoshima,
Thanks for stepping up! Go ahead, give it a try. I'm here to help along the way.

**Comment by avitorio** [comment]
@ZiyadBoshima @city41 This has been added to Outstatic and will be released in the next minor version. Thank you!!
