### ISSUE TITLE
Dashboard doesn't show default demo collections

### ISSUE THREAD

**Issue by b2bcreative** [avitorio/outstatic#164]
### Provide environment information

Outstatic 1.0.3, Next 13.5.4, React 18

### What browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

I deployed the demo in the docs, connected correctly with Github and filled out correctly the required environment variables. The problem is that the /outstatic dashboard is empty, doesn't recognize the existence of the "posts" and "projects" collections present in the demo. On the other hand, the blog itself renders the posts and projects correctly. Rebuilding metadata doesn't work, the button stays as "Rebuilding..." indefinitely.

![image](https://github.com/avitorio/outstatic/assets/150729792/52743b67-08be-43f1-ab46-3b85cd4a9c38)

### Expected Behavior

I expected Posts and Projects to exist in the dashboard.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://blog-seven-jade-88.vercel.app/

### To Reproduce

Follow all docs instructions to connect with Github and deploy the demo on Vercel.

**Comment by b2bcreative** [comment]
Hi, no errors

**Comment by b2bcreative** [comment]
Hi @avitorio, no errors.

**Comment by avitorio** [comment]
@b2bcreative I think I found the issue and pushed a fix. Can you try redeploying your website on Vercel and let me know if it works now?

**Comment by b2bcreative** [comment]
@avitorio the rebuild metadata console error is gone, but collections still don't show

**Comment by avitorio** [comment]
Can you share your environment OST environment variables, except for the github ones?

**Comment by b2bcreative** [comment]
@avitorio
OST_REPO_SLUG=blog
OST_REPO_BRANCH=master
OST_REPO_OWNER=b2bcreative
OST_CONTENT_PATH=outstatic/content
OST_MONOREPO_PATH=apps/web

**Comment by avitorio** [comment]
You probably don't need the `OST_MONOREP_PATH` env var. Try removing it and redeploying.

**Comment by avitorio** [comment]
Have you redeployed after making the changes? Can you give me access to the repo?

**Comment by b2bcreative** [comment]
Oh man, I forgot to redeploy this time, sorry. But it worked!! The problem was definitely the `OST_MONOREP_PATH` var. Thank you a lot for your help!!

![image](https://github.com/avitorio/outstatic/assets/150729792/d8066b97-9536-4e62-bec3-ad0080e1ab63)

**Comment by avitorio** [comment]
No problem. Glad you fixed it.
