### ISSUE TITLE
Add an explicit error message when the outstatic target branch does not exist

### ISSUE THREAD

**Issue by qlereboursBS** [avitorio/outstatic#17]
I tried to create my first collection, and nothing happened (loading forever). After opening the console, I found this message:
`error: "Variable $input of type CreateCommitOnBranchInput! was provided invalid value for expectedHeadOid (Expected value to not be null)"`

Finally, when going to the network, I discovered that the commit was being created on a `main` branch, that didn't exist on my brand new repository.

It would improve user experience if there was an detailed error message to explain that it's impossible to commit on the repository because the branch is not found.

Would it be possible?
Thanks

**Comment by avitorio** [comment]
@qlereboursBS Thanks for flagging. I'll take a look at it.

**Comment by avitorio** [comment]
Hey @qlereboursBS, I just wanted to let you know the latest version of Outstatic `v0.0.30-rc` introduces a OST_REPO_BRANCH environment variable that lets you specify the branch you want. 

As for the error message, we are going to work on it soon. I'll leave this issue open as a reminder until we get it done. Thanks!

**Comment by avitorio** [comment]
@qlereboursBS the error message when a collection can't be created is already merged and will be available in our next version.
