### ISSUE TITLE
Moblie version doest not allow editing

### ISSUE THREAD

**Issue by dimonb** [avitorio/outstatic#179]
### Provide environment information

Any environment

### Describe the Bug

If shrink window to mobile screen size, block with page edit disappear

### Expected Behavior

Ability to edit pages on moblie version of site

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

no link

### To Reproduce

just shrink window

https://github.com/avitorio/outstatic/assets/2246980/3a757bef-2d71-484d-948e-ac7302b4a268

**Comment by avitorio** [comment]
Thanks for flagging this!

**Comment by avitorio** [comment]
@dimonb this has been fixed and the changes will be applied to the next version of Outstatic
