### ISSUE TITLE
Bug: Cover Image

### ISSUE THREAD

**Issue by lexstefan** [avitorio/outstatic#186]
### Provide environment information

Package Versions:

"next": "14.1.0",
"outstatic": "^1.3.0",

### What browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

localhost:3000

### Describe the Bug

Proceeded to follow "Add To Next.js" instructions from documentation. Everything ran perfectly until i added coverImage for products collections. Inconsistent behavior with coverImage

### Expected Behavior

Whenever i edit a collection item [product / post] i expect the previously uploaded coverImage to show up. Feedback if there is an error uploading the image.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://not-required.com

### To Reproduce

1. add a product or post, add title, add description, add coverImage
2. set to published & save
3. git pull --rebae [to get content from github on localhost]
4. navigate around inside outstatic, here and there
5. go back to same product to add additional details in the editor [**at this point the previously uploaded image is no longer present / shows up in editor**]
6. save the document
7. git pull --rebase again, and we can clearly see that the coverImage from the markdown file was deleted cleared
8. at this point i tried uploading the exact same image and i got no feedback, but the image was not uploading [maybe github threw an error because it's the same image]

**Comment by lexstefan** [comment]
P.s.: I switched the coverPhoto to link, saved, then back to upload just so i can use that field again. I think it got cleared or something.

**Comment by avitorio** [comment]
I got that error when uploading a file recently but couldn't replicate it.

What filetype were you trying to upload? Jpeg?

**Comment by lexstefan** [comment]
Hello, was png and webp.

**Comment by philals** [comment]
Hi @avitorio . Great project! The only git based CMS I managed to get working with no issues first time.

I have something simular. Fresh install on Vercel.

I click to edit a post and ONLY add an "!" on the title. This results in this diff: https://github.com/philals/outstatic-blog/commit/e3e18955074e863d3e098cd82455600368fb5cd2#diff-91152342c460b4e6bd7368b5061c6cf71990798542f61996812fcb91bf91d965L2

I don't click any of the side menu.

Hope this helps

**Comment by avitorio** [comment]
@philals Oh wow, thanks for flagging this! I'll look into it asap!

**Comment by avitorio** [comment]
Thank you @lexstefan and @philals - this has been fixed and will be available in the next minor release
