### ISSUE TITLE
Commits to main branch

### ISSUE THREAD

**Issue by sanderfish** [avitorio/outstatic#19]
I'm trying Outstatic locally in a feature branch, but my changes are automatically being committed to the `main` branch.

1. It should commit changes to the current branch
2. When working on localhost, maybe it shouldn't push commits at all?

**Comment by avitorio** [comment]
Hi @sanderfish,

There is already a PR for setting up the branch on .env. This should be ready today.

As for working in localhost, I've considered this possibility but it added a bunch of complexity to the system. For now I favored having a single source of truth for the documents, which allowing for saving on localhost wouldn't provide.

In the end you can always set documents as a `draft` if you don't want to have the go live after saving.
