### ISSUE TITLE
Deploy via SST and Outstatic leads to error.

### ISSUE THREAD

**Issue by ccfai8** [avitorio/outstatic#225]
### Provide environment information

    "outstatic": "^1.4.7",
    "next": "^14.2.3",
    "react": "^18.2.0",

### Describe the Bug

I deployed my app on Vercel and when i visit a slug page under post or page, it works well.
But if i deployed my app using SST, then error occurs if visiting a slug page under post or page.

Error:
You installed esbuild for another platform than the one you're currently using. This won't work because esbuild is written with native code and needs to install a platform-specific binary executable. Specifically the "@esbuild/darwin-arm64" package is present but this platform needs the "@esbuild/linux-x64" package instead. People often get into this situation by installing esbuild on Windows or macOS and copying "node_modules" into a Docker image that runs Linux, or by copying "node_modules" between Windows and WSL environments. If you are installing with npm, you can try not copying the "node_modules" directory when you copy the files over, and running "npm ci" or "npm install" on the destination platform after the copy. Or you could consider using yarn instead of npm which has built-in support for installing a package on multiple platforms simultaneously. If you are installing with yarn, you can try listing both this platform and the other platform in your ".yarnrc.yml" file using the "supportedArchitectures" feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures Keep in mind that this means multiple copies of esbuild will be present. Another alternative is to use the "esbuild-wasm" package instead, which works the same way on all platforms. But it comes with a heavy performance cost and can sometimes be 10x slower than the "esbuild" package, so you may also not want to do that.

### Expected Behavior

Can visit the slug page or post even deployed via SST

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://outstatic-web.vercel.app/docs/getting-started#deploy-with-vercel

### To Reproduce

N/A

**Comment by avitorio** [comment]
This issue has become stale/
