### ISSUE TITLE
Vercel Digest: 1228582423

### ISSUE THREAD

**Issue by dominicdev** [avitorio/outstatic#239]
### Provide environment information

"outstatic": "^1.4.7",
"next": "^14.2.3",
"react": "^18.2.0",

### Describe the Bug

I'm trying to create a page with slug, now I want to get all the post but im getting error in vercel, it worked in local build,
I'm trying to use get all the code 
`  const db = await load()

  const allPosts = await db
    .find({ collection: 'posts' }, [
      'title',
      'publishedAt',
      'slug',
      'coverImage',
      'description',
      'tags',
      "author",
      "category",
      "status"
    ])
    .sort({ publishedAt: -1 })
    .toArray()
 

  return { 
    allPosts 
  }`

I think there is error when using dynamic page 

### Expected Behavior

this error was only in vercel 
![image](https://github.com/user-attachments/assets/27715bfa-d230-41f7-b1cd-cddebf901b7a)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://nextcms2.vercel.app/

### To Reproduce

I try to clone the updated repo, then create a separate slug 
thos this imple code 

` 
 
import Layout from '@/components/Layout'
import { load } from 'outstatic/server'
 

export default async function Search({params}) {
  const {allPosts} = await getData()
 
  return ( 
    <main className=' h-full min-h-screen bg-[#E6E8E6] text-black'>
    <div className="font-sans ">
     
      <main className="container max-w-[1068px] mx-auto mt-8 flex flex-col ">
       
      </main> 
      
    </div>
  </main>
 
  )
}

async function getData() {
  const db = await load()

  const allPosts = await db
    .find({ collection: 'posts' }, [
      'title',
      'publishedAt',
      'slug',
      'coverImage',
      'description',
      'tags',
      "author",
      "category",
      "status"
    ])
    .sort({ publishedAt: -1 })
    .toArray()
 

  return { 
    allPosts 
  }
}
`

**Comment by avitorio** [comment]
Outstatic won't work with dynamic rendering. You should turn the page static using generateStaticPaths or `export const dynamic = 'force-static'`
