### ISSUE TITLE
Cannot read properties of null (reading 'query') on Next v13

### ISSUE THREAD

**Issue by mzalevski** [avitorio/outstatic#29]
on `http://localhost:3000/outstatic`

I double checked the getting started config & it is correct

```
Server Error

TypeError: Cannot read properties of null (reading 'query')
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

**Comment by chaosparadox** [comment]
@avitorio Hii, I'm having the same issue as OP and I'm on v12.2.5 - Any suggestions? The idea of Outstatic is amazing so I'm really hoping to make it work!

**Comment by avitorio** [comment]
Hey @chaosparadox and @mzalevski - I've just launched version `0.0.32-rc` of Outstatic which gives support for Next.js 13 and also offers backwards compatibility to some versions of Next.js 12 including `12.2.5`

**Comment by mzalevski** [comment]
@avitorio I get 404 on: http://localhost:3000/api/outstatic/login

**Comment by avitorio** [comment]
Hey @mzalevski,
This is odd. What are the contents of your `pages/api/outstatic/[[...ost]].tsx` file?
What versions of `next` and `outstatic` are you on?

**Comment by mzalevski** [comment]
Oh, I see what's wrong. I created another `api` folder in an existing `api` folder. My bad. It does work now. Sorry.
