### ISSUE TITLE
Once I add new collection, it doesn't show on the left sidebar

### ISSUE THREAD

**Issue by leonace924** [avitorio/outstatic#32]
![image](https://user-images.githubusercontent.com/42954461/198697055-5d6afb8b-7e06-4505-96b1-80176ef9b9d9.png)

It doesn't show Projects on the left sidebar
I set all in the authorization

It shows this error

message

`"Variable $input of type CreateCommitOnBranchInput! was provided invalid value for expectedHeadOid (Expected value to not be null)"`

I am pushing to `staging` branch, and I test it on the localhost:3000

What did I do wrong?

Thanks

**Comment by avitorio** [comment]
Have you set the `OST_REPO_BRANCH` environment variable to `staging`?

**Comment by leonace924** [comment]
![image](https://user-images.githubusercontent.com/42954461/198699814-95d9d12d-50da-4702-911b-05ad89734f91.png)

Yes, this is my env file

**Comment by avitorio** [comment]
What version of Next.js are you on?

**Comment by leonace924** [comment]
I am on 12.3.1

![image](https://user-images.githubusercontent.com/42954461/198702313-d128a127-255a-4307-962d-906a213439c1.png)

**Comment by avitorio** [comment]
Try upgrading to `outstatic@^0.0.30-rc` - the `OST_REPO_BRANCH` feature was only added on this version.
