### ISSUE TITLE
Is there an elegant way to update the version of outstatic?

### ISSUE THREAD

**Issue by Summpot** [avitorio/outstatic#39]
Although it is possible to change package.json directly from the local repository to update the outstatic version, what is the reason to clone a local repository if all our content updates only need to be done in the dashboard?
Is it possible to add a button to update the outstatic version in the dashboard?

**Comment by avitorio** [comment]
Hey,

I haven't thought about this before.

It is possible.

We'd need to make sure the button isn't available on versions with breaking changes...

I am afraid we of messing with people's package.json...

Can you start a discussion in the ideas channel for us to think about possible ways this could work or go wrong?

**Comment by avitorio** [comment]
Closed for this: https://github.com/avitorio/outstatic/discussions/41
