### ISSUE TITLE
React and React-DOM version requirements

### ISSUE THREAD

**Issue by mattjared** [avitorio/outstatic#45]
Hey! I was on react / react-dom version 17.0.2 and was getting a "useHook" error when trying to load `localhost:3000/outstatic`. I upgraded to 18.2 on both and outstatic is loading. I know there's a lot of issues with dependencies right now but might be something to clarify upfront if possible what the requirements are to help with troubleshooting.

I'm up and running now though, thanks for making this!

**Comment by avitorio** [comment]
Hi @mattjared,

I have tested locally with react and react-dom `17.0.2` and Next.js `12.3.2` and it works.
Can you also let me know the Next.js version you were using? Thanks.

**Comment by avitorio** [comment]
Hey @mattjared,
I'm closing this now, but feel free to reach out in case you're still facing this.
