### ISSUE TITLE
Examples/blog while using Tailwind it does not react to system theme changes (light/dark)

### ISSUE THREAD

**Issue by juicecultus** [avitorio/outstatic#59]
### Provide environment information

No matter what setting I include into Tailwind, I cannot get the UI to switch to dark mode. I'm on the latest version - "outstatic": "^0.0.33-rc"

### What browser are you using? (if relevant)

Used with Chrome and Safari on MacOS and iOS,

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Despite writing all the "dark:" classes into the UI, and being on dark mode system wide, the example blog does not switch. Is there a setting anywhere in the code preventing dark mode from kicking in? I've checked the configs for Tailwind and the CSS files but couldn't see any issue there. 

### Expected Behavior

When a dark: class is inserted into a component, the default behaviour in Tailwind is that it will be applied if "prefers-dark-mode" is enabled. This does not happen with the Outstatic example/blog 

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/avitorio/outstatic/tree/main/examples/blog

### To Reproduce

Insert dark: class into UI components, enable dark mode system wide in MacOS and expect the example/blog to apply dark settings

**Comment by avitorio** [comment]
Hi @juicecultus, thanks for flagging this. I'll look into it.

**Comment by juicecultus** [comment]
@avitorio - please don't waste your time, I've double checked earlier and it was simply a conflict with my DaisyUI plugin. 
The example works as expected, no bugs :).

**Comment by avitorio** [comment]
Cool. Thanks for letting me know @juicecultus. I hope you have a good experience with Outstatic!
