### ISSUE TITLE
Support for .mdx files

### ISSUE THREAD

**Issue by avitorio** [avitorio/outstatic#73]
As mentioned by [this comment](https://github.com/avitorio/outstatic/issues/50#issuecomment-1315636862), `.mdx` files are not being fetched.

To make this work we'd need to update:

- `getDocumentBySlug` to check for `mdx` files in case the `md` version is not available.
- `list.tsx`
-  `/edit-documet/index.tsx`

I'm not entirely sure how the editor would handle `.mdx` files, so this might require some investigation.

**Comment by Bowens20832** [comment]
Hey @avitorio I am interested in exploring this topic 😄

**Comment by avitorio** [comment]
Hi @Bowens20832 , thanks for stepping up! 

I think there are a few steps to this issues, this is just an inital idea:

1 - Make .mdx the default file type for Outstatic, with fallback support for .md

2 - Allow react components that are inside mdx files to be rendered in the editor.

3 - Expand the editor to use custom react components

**Comment by Bowens20832** [comment]
@avitorio Yes to all of the above! I think I can handle everything you mentioned, plus a bunch more 😄 

I have some ideas and improvements for Outstatic, and I think we could collobarate together..

Would it be okay for me to schedule a time to chat with you from your calendar on Pacy.co?

**Comment by Bowens20832** [comment]
> Hey @Bowens20832, please send an email to [hello@outstatic.com](mailto:hello@outstatic.com). We'll figure something out.

Awesome! I'll send something over in a little bit 🚀 

![image](https://github.com/avitorio/outstatic/assets/10189130/f2ddd1df-360a-42d0-a532-a95d254b0408)

**Comment by dmarkbreiter** [comment]
Is this feature prioritized? I absolutely adore Outstatic and think it has a lot of potential, but no `.mdx` support is the main thing stopping me from using it on actual projects.

**Comment by avitorio** [comment]
Hey @dmarkbreiter yes it is. I have a solution almost ready for it but am just lacking the time to properly launch it. It may bring in some breaking changes and compatibility issues with older versions, so I think this will come in the next major update.

**Comment by pan-tales** [comment]
+1 this would be huge

**Comment by kaziridwan** [comment]
+1

**Comment by wutsqo** [comment]
How far the progress of this feature has been going on? I'd love to contribute as well if you need additional hands

**Comment by avitorio** [comment]
@wutsqo thanks for the offer. There's a big update coming soon.

**Comment by DarkNeedle** [comment]
Andre will the new update be forthcoming in the coming weeks or more months. MDX is very important to most for this. Just curious, thanks

**Comment by avitorio** [comment]
Hey @DarkNeedle, it will be coming soon. No hard deadline but most likely mid-September to early October.

**Comment by seanaguinaga** [comment]
Completed!? 💯

**Comment by avitorio** [comment]
Hey @seanaguinaga, @MoeKanan
The canary version currently supports reading and saves as mdx by default.
No support for components yet though. I'm working on it.

**Comment by wasinsandiego** [comment]
The MDX output works well! Until support for mdx components ships, I'm using a workaround that isn't too bad. Thought it might be useful for others.

Manually start a code block with a made up language name for syntax highlighting. I am using `component`, like this:
```
```component
```

When you it enter/return, it changes into that code block UI in the editor. Paste your MDX component code in there. Just don't mess with that little select menu for the language type.
> ![Image](https://github.com/user-attachments/assets/2e2f176d-2c57-42d0-8298-a88a316cbb7b)

The markdown in your mdx file comes through like this.
> ![Image](https://github.com/user-attachments/assets/cd4c5ed5-cb28-4ff4-96ab-d1ef3f69611d)

<br />

In your react app, just process the mdx source string before passing into an MDX compiler.
```javascript
markdownSource.replace(/```component\s*([\s\S]*?)\s*```/g, '$1')
```

Can't wait to see how it may be supported in the editor.

**Comment by avitorio** [comment]
Hey @wasinsandiego,

This is such a cool workaround. Thank you for sharing. I'll add it to the docs!
