### ISSUE TITLE
Getting error: NextRouter was not mounted.

### ISSUE THREAD

**Issue by mikealche** [avitorio/outstatic#78]
### Provide environment information

Tried using the 0.0.34-rc version which is what you get when you run `yarn add outstatic` right now. 
And also tried downgrading to `0.0.33-rc`.

Getting the same error with both. 

My next version is `12.0.1`

### What browser are you using? (if relevant)

chrome

### Describe the Bug

Would love to give more details, but unfortunately, the error doesn't give any line number or anything. :(

### Expected Behavior

Would love to be able to get to this screen
![image](https://user-images.githubusercontent.com/8585011/204301205-b4c3cfbe-0c32-4ae3-956d-e81ca89cda02.png)

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

-

### To Reproduce

-

**Comment by avitorio** [comment]
Thanks. I'll look into it.

**Comment by avitorio** [comment]
Hey @mikealche, I was trying to fix this error and while I can replicate it locally, it might take a while for a fix. But I noticed you may be able to run `0.0.31-rc` on your site. If not, try upgrading next to `^12.0.0`. Let me know if any of these work. Thanks!

**Comment by mikealche** [comment]
heyy, thanks for the reply! 
Version 31 gives me `TypeError: Cannot destructure property 'session' of 't' as it is undefined.`

But I'll keep trying. 

is it because of my Next version? should I update/downgrade?

**Comment by avitorio** [comment]
Hey @mikealche, this might have to do with your Next.js version. Try upgrading to a version above `12.2.0` or perhaps `13.0.0` to be able to work with newer versions of outstatic.

**Comment by amesas** [comment]
> Hey @mikealche, this might have to do with your Next.js version. Try upgrading to a version above `12.2.0` or perhaps `13.0.0` to be able to work with newer versions of outstatic.

As I commented on #74 we have the same problem on Next 12.3 and Next 13.0 and with Outstatic 0.33 and 0.34.

Never tried 0.31

**Comment by avitorio** [comment]
Hey @amesas, it should work with `0.0.31-rc`. We've switched the internal version of Next.js to 13 on `0.0.32-rc`, so I think that's what causes the error. I'm not entirely sure if we can make it so `outstatic` uses the version of Next.js that you have installed. I'll see if I find a solution for it. Perhaps with `peerDependencies`, but if that isn't an option we might just have to stick with providing new versions for 13 only, since that's where Next.js is moving towards.

**Comment by avitorio** [comment]
Hey @amesas, @mikealche and @jakobo. I've just published new version of outstatic `0.0.35-rc` which uses next as a `peerDependency` something I should've done from the get go. It should now work with next.js above `12.2.5` and also on `ˆ13.0.0`. The `NextRouter was not mounted` seems to be gone.
