### ISSUE TITLE
Application error when i try to add new collection

### ISSUE THREAD

**Issue by SESIRE-Marketing** [avitorio/outstatic#94]
### Provide environment information

![image](https://user-images.githubusercontent.com/121179360/222383854-ad8ef21d-cc12-45cf-9726-22978e87fa10.png)

### What browser are you using? (if relevant)

google chrome

### How are you deploying your application? (if relevant)

vercel

### Describe the Bug

with localhost everything works fine but when i tried with vercel live url it's give application error, and in console display the error "TypeError: Cannot read properties of undefined (reading 'refs')".

### Expected Behavior

successfully i want to add new collection

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://sesire-blogs-kappa.vercel.app/outstatic/collections/new

### To Reproduce

https://sesire-blogs-kappa.vercel.app/outstatic/collections/new

**Comment by avitorio** [comment]
Hey,
Are you able to perform other actions on `/outstatic` on vercel? Like editing a post, etc...?

**Comment by Socials-SESIRE** [comment]
Hey Andre

Adding in Mitesh who raised this.

Thanks!

**Comment by miteshkavar1996** [comment]
Hey, Andre
No, i can saw only my blog list and when i tried to add blog, edit blog or create a new collection then it's give this error
and it's only happned with the live vercel url, on localhost it's working good

when i open console and check the error, it's display type error: undefined refs

**Comment by avitorio** [comment]
Hey @miteshkavar1996, can you create a demo public repository with your setup for me to take a look? Would you be able to share your vercel environment variables (**excluding** the GITHUB Auth ones)?
There's probably an error with one of the environment variables...

**Comment by slavb18** [comment]
Hi!

Just generated and published blog https://github.com/slavb18/iblog
on https://iblog-omega.vercel.app/

logged in,  and cannot add page/project/etc:

framework-73b8966a3c579ab0.js:9 TypeError: Cannot read properties of undefined (reading 'refs')
    at ref (906-0f22efec3fa3b7b5.js:179:217244)
    at c (906-0f22efec3fa3b7b5.js:179:234073)
    at 906-0f22efec3fa3b7b5.js:179:234227
    at uU (framework-73b8966a3c579ab0.js:9:84246)
    at uY (framework-73b8966a3c579ab0.js:9:91416)
    at e (framework-73b8966a3c579ab0.js:9:111124)
    at framework-73b8966a3c579ab0.js:9:111135
    at oI (framework-73b8966a3c579ab0.js:9:111647)
    at oS (framework-73b8966a3c579ab0.js:9:95017)
    at x (framework-73b8966a3c579ab0.js:33:1373)
a5 @ framework-73b8966a3c579ab0.js:9
a.componentDidCatch.t.callback @ framework-73b8966a3c579ab0.js:9
lH @ framework-73b8966a3c579ab0.js:9

**Comment by Socials-SESIRE** [comment]
Hey Andre

I'm adding in @Vaionex ***@***.***> here as Mitesh is no longer
working on this.

Cheers!

**Comment by Socials-SESIRE** [comment]
Hi all.

Can we prioritize checking this as we need to make amendments to current
blog posts and add in additional ones we've acquired.

**Comment by avitorio** [comment]
This is most likely a misconfiguration of environment variables. I've asked for examples of the env vars in use (exclusing github auth) but never got it.

**Comment by Socials-SESIRE** [comment]
Ok thanks for letting me know Andre.

@Vaionex ***@***.***> @***@***.*** ***@***.***>

Do you mind assigning someone to this?

**Comment by SESIRE-Marketing** [comment]
Adding in @***@***.*** ***@***.***> - hopefully he can
take charge on this

**Comment by SESIRE-Marketing** [comment]
Hey Andre.

We never got this fixed - can you please let me know what's the best way to
proceed?

**Comment by avitorio** [comment]
Please, reach out to hello@outstatic.com for support.
